export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';

export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// order list for normal user profile
export const ORDER_LIST_USER_REQUEST = 'ORDER_LIST_USER_REQUEST';
export const ORDER_LIST_USER_SUCCESS = 'ORDER_LIST_USER_SUCCESS';
export const ORDER_LIST_USER_FAIL = 'ORDER_LIST_USER_FAIL';
export const ORDER_LIST_USER_RESET = 'ORDER_LIST_USER_RESET';

// order list for admin
export const ORDER_LIST_ADMIN_REQUEST = 'ORDER_LIST_ADMIN_REQUEST';
export const ORDER_LIST_ADMIN_SUCCESS = 'ORDER_LIST_ADMIN_SUCCESS';
export const ORDER_LIST_ADMIN_FAIL = 'ORDER_LIST_ADMIN_FAIL';

export const ORDER_PAYMENT_REQUEST = 'ORDER_PAYMENT_REQUEST';
export const ORDER_PAYMENT_SUCCESS = 'ORDER_PAYMENT_SUCCESS';
export const ORDER_PAYMENT_FAIL = 'ORDER_PAYMENT_FAIL';
export const ORDER_PAYMENT_RESET = 'ORDER_PAYMENT_RESET';

export const ORDER_DELIVERY_REQUEST = 'ORDER_DELIVERY_REQUEST';
export const ORDER_DELIVERY_SUCCESS = 'ORDER_DELIVERY_SUCCESS';
export const ORDER_DELIVERY_FAIL = 'ORDER_DELIVERY_FAIL';
export const ORDER_DELIVERY_RESET = 'ORDER_DELIVERY_RESET';
